"""Docker sandbox runner.

Every container is started with:

  --network none            (test mode; API mode uses a loopback-only publish)
  --cpus / --memory         hard resource caps
  --pids-limit              fork-bomb protection
  --read-only               immutable root filesystem
  --tmpfs /tmp              small writable scratch, noexec/nosuid
  --cap-drop ALL            no privileged capabilities
  --security-opt no-new-privileges
  --user (non-root on posix)
  no host docker socket, no host mounts other than the project workspace
  a scrubbed environment: OPENAI_API_KEY is never passed in

The base image is built once with the runtime dependencies preinstalled, so the
sandbox itself never needs network access to run a project.
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
from pathlib import Path

from ..config.settings import Settings
from ..security.execution_security import assert_no_secrets, scrub_env
from ..utils.logging import get_logger
from .process_manager import ProcessResult, run_process
from .sandbox import Sandbox, SandboxCapabilities

logger = get_logger(__name__)

SANDBOX_IMAGE_TAG = "api-doctor-sandbox:py312"
WORKSPACE_MOUNT = "/workspace"

# Preinstalled so a `--network none` container can still run a FastAPI project.
SANDBOX_PACKAGES = [
    "fastapi", "uvicorn[standard]", "httpx", "pytest", "pytest-asyncio",
    "pydantic", "python-multipart", "requests", "sqlalchemy", "anyio",
]

DOCKERFILE = f"""# Auto-generated by API Doctor. Base image for the execution sandbox.
FROM {{base}}
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1
RUN pip install --no-cache-dir {' '.join(SANDBOX_PACKAGES)}
RUN useradd --create-home --uid 10001 sandbox || true
WORKDIR {WORKSPACE_MOUNT}
"""


class DockerRunner(Sandbox):
    kind = "docker"

    def __init__(self, settings: Settings) -> None:
        super().__init__(settings)
        self._image_ready: bool | None = None
        self._image_lock = asyncio.Lock()

    # ------------------------------------------------------------ daemon ---
    async def available(self) -> bool:
        if not self.settings.docker_available:
            return False
        result = await self._docker(["version", "--format", "{{.Server.Version}}"], timeout=20)
        if result.exit_code != 0:
            logger.warning("docker daemon not reachable: %s", (result.stderr or result.stdout)[:200])
            return False
        return True

    async def _docker(self, args: list[str], *, timeout: float = 60) -> ProcessResult:
        env = scrub_env()
        assert_no_secrets(env)
        return await run_process(
            ["docker", *args], cwd=Path.cwd(), env=env, timeout=timeout
        )

    # ------------------------------------------------------------- image ---
    async def ensure_image(self) -> bool:
        async with self._image_lock:
            if self._image_ready is not None:
                return self._image_ready
            inspect = await self._docker(["image", "inspect", SANDBOX_IMAGE_TAG], timeout=30)
            if inspect.exit_code == 0:
                self._image_ready = True
                return True
            logger.info("building sandbox image %s (one-time, ~1-2 min)", SANDBOX_IMAGE_TAG)
            context = self.settings.data_dir / "sandbox-image"
            context.mkdir(parents=True, exist_ok=True)
            (context / "Dockerfile").write_text(
                DOCKERFILE.format(base=self.settings.docker_image), encoding="utf-8"
            )
            build = await self._docker(
                ["build", "-t", SANDBOX_IMAGE_TAG, "-f", str(context / "Dockerfile"), str(context)],
                timeout=900,
            )
            self._image_ready = build.exit_code == 0
            if not self._image_ready:
                logger.error("sandbox image build failed: %s", (build.stderr or build.stdout)[-1500:])
            return self._image_ready

    # ------------------------------------------------------ capabilities ---
    def capabilities(self) -> SandboxCapabilities:
        return SandboxCapabilities(
            kind="docker",
            isolated=True,
            network=self.settings.docker_network,
            limits=self.limits,
            description=(
                f"Docker sandbox ({SANDBOX_IMAGE_TAG}). Project code runs in a container with "
                f"{self.limits.cpus} CPU, {self.limits.memory} memory, {self.limits.pids} PID limit, "
                "all capabilities dropped, a read-only root filesystem and no backend secrets."
            ),
            warnings=[
                "API mode publishes the project port on 127.0.0.1 only; the container "
                "still needs a network namespace for that, unlike test mode which uses --network none.",
            ],
        )

    # ----------------------------------------------------------- run args ---
    def _security_args(self) -> list[str]:
        args = [
            "--cap-drop", "ALL",
            "--security-opt", "no-new-privileges",
            f"--cpus={self.limits.cpus}",
            f"--memory={self.limits.memory}",
            f"--memory-swap={self.limits.memory}",
            f"--pids-limit={self.limits.pids}",
            "--tmpfs", f"/tmp:rw,noexec,nosuid,size={self.limits.tmpfs_size}",
        ]
        if self.limits.read_only_rootfs:
            args.append("--read-only")
        if sys.platform != "win32":
            # Match the host uid so files written into the mounted workspace stay
            # owned by the backend user. On Windows the bind mount is translated
            # by Docker Desktop and uid mapping does not apply.
            args += ["--user", f"{os.getuid()}:{os.getgid()}"]  # type: ignore[attr-defined]
        return args

    def _env_args(self, extra: dict[str, str] | None) -> list[str]:
        env = {
            "PYTHONDONTWRITEBYTECODE": "1",
            "PYTHONUNBUFFERED": "1",
            "PYTHONPATH": WORKSPACE_MOUNT,
            "API_DOCTOR_SANDBOX": "1",
            "HOME": "/tmp",
        }
        if extra:
            env.update(extra)
        assert_no_secrets(env)
        args: list[str] = []
        for key, value in env.items():
            args += ["-e", f"{key}={value}"]
        return args

    def build_run_command(
        self,
        python_args: list[str],
        *,
        workspace: Path,
        network: str | None = None,
        publish: tuple[int, int] | None = None,
        extra_env: dict[str, str] | None = None,
    ) -> list[str]:
        """Assemble a `docker run` argv. No shell, no model-supplied strings."""
        source = str(workspace.resolve())
        command = [
            "docker", "run", "--rm", "-i",
            "--mount", f"type=bind,source={source},target={WORKSPACE_MOUNT}",
            "--workdir", WORKSPACE_MOUNT,
        ]
        command += self._security_args()
        command += self._env_args(extra_env)
        resolved_network = network or self.settings.docker_network
        if publish is not None:
            host_port, container_port = publish
            command += ["-p", f"127.0.0.1:{host_port}:{container_port}"]
            if resolved_network == "none":
                resolved_network = "bridge"
        command += ["--network", resolved_network]
        command += [SANDBOX_IMAGE_TAG, "python", *python_args]
        return command

    # --------------------------------------------------------------- run ---
    async def run_python(
        self,
        args: list[str],
        *,
        workspace: Path,
        timeout: float | None = None,
        extra_env: dict[str, str] | None = None,
    ) -> ProcessResult:
        if not await self.ensure_image():
            return ProcessResult(
                exit_code=125,
                stdout="",
                stderr=f"sandbox image {SANDBOX_IMAGE_TAG} is not available; cannot run in docker mode",
                duration_ms=0,
                command=["docker"],
                cwd=str(workspace),
            )
        command = self.build_run_command(args, workspace=workspace, extra_env=extra_env)
        env = scrub_env()
        assert_no_secrets(env)
        return await run_process(
            command,
            cwd=workspace,
            env=env,
            timeout=timeout or self.settings.execution_timeout_seconds,
        )

    async def ensure_dependencies(self, workspace: Path, packages: list[str]) -> ProcessResult | None:
        """The sandbox image ships the common stack; nothing is installed at run time.

        Installing from an uploaded manifest would require network access inside
        the sandbox and would execute arbitrary `setup.py` code, so we do not.
        """
        if not packages:
            return None
        missing = await self.missing_packages(workspace, packages)
        if missing:
            logger.info("sandbox image lacks %s; project may fail to import", ", ".join(missing))
        return None

    async def missing_packages(self, workspace: Path, packages: list[str]) -> list[str]:
        probe = (
            "import importlib.util,json;"
            f"names={packages!r};"
            "print(json.dumps([n for n in names if importlib.util.find_spec(n) is None]))"
        )
        result = await self.run_python(["-c", probe], workspace=workspace, timeout=60)
        if result.exit_code != 0:
            return []
        for line in reversed(result.stdout.strip().splitlines()):
            try:
                return json.loads(line)
            except ValueError:
                continue
        return []
